# This is a basic workflow to help you get started with Actions

name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: "1 */5 * * *"  # Every 5 hours at minute 1

jobs:
  build:
    concurrency:
      group: bot-run
      cancel-in-progress: false

    runs-on: ubuntu-latest
    timeout-minutes: 355  # Slightly under GitHub 6h limit

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0

      - name: Inject Secret Token
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml

      - name: Make Stockfish Executable
        run: chmod +x ./engines/stockfish-ubuntu-x86-64-avx2

      - name: Run Bot
        run: python -u user_interface.py --matchmaking

      - name: 🔁 Self-Restart Workflow
        if: always()  # Even if the bot crashes
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot.yml/dispatches \
            -d '{"ref":"main"}'
