name: Query Titans Book

on:
  workflow_dispatch:

jobs:
  check-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print book moves after 1.e4 e5 2.Nf3 Nc6 3.Bb5
        run: |
          # Clone LyGlot and build
          git clone https://github.com/torom76/lyglot.git
          cd lyglot && make && cd ..

          # Create a position in FEN after 1.e4 e5 2.Nf3 Nc6 3.Bb5
          # That's the Ruy Lopez position
          FEN="r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 2 3"

          # Query the book
          ./lyglot/lyglot engines/titans.bin "$FEN"

