name: Query Titans Book

on:
  workflow_dispatch:

jobs:
  query-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install polyglot tool
        run: |
          sudo apt-get update
          sudo apt-get install -y polyglot

      - name: Query opening book
        run: |
          echo "e4 e5 Nf3 Nc6 Bb5" > input.moves
          polyglot book=engines/Titans.bin verbose verbose option=OwnBook value=true eval=eval.txt > output.txt 2>&1 || true
          echo "::group::Opening Book Output"
          cat output.txt
          echo "::endgroup::"
