name: Download and Check Book

on:
  workflow_dispatch:

jobs:
  fetch-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make engines folder
        run: mkdir -p engines

      - name: Download book from PixelDrain
        run: |
          echo "📥 Downloading book..."
          curl -L --retry 5 --retry-delay 3 "https://pixeldrain.com/api/file/gQziifHp?download" -o engines/ruylopez_book.bin

      - name: Check book file size
        run: |
          FILE="engines/ruylopez_book.bin"
          if [ ! -f "$FILE" ]; then
            echo "❌ Book file not found!"
            exit 1
          fi

          SIZE=$(stat -c %s "$FILE")
          echo "Downloaded size: $SIZE bytes"

          if [ "$SIZE" -lt 16384 ] || [ $((SIZE % 16)) -ne 0 ]; then
            echo "❌ Invalid book: size must be ≥16KB and multiple of 16"
            exit 1
          fi

          echo "✅ Book size valid"

      - name: Commit book to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add engines/ruylopez_book.bin
          git commit -m "Add valid Ruy Lopez book"
          git push
