name: Download Book from PixelDrain

on:
  workflow_dispatch:

jobs:
  download-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download from PixelDrain
        run: |
          mkdir -p engines
          curl -L "https://pixeldrain.com/api/file/gQziifHp" -o engines/book.bin

      - name: Show file size
        run: |
          ls -lh engines/book.bin

      - name: Trim to 100MB if too large (optional)
        run: |
          MAX_BYTES=$((100 * 1024 * 1024))
          ACTUAL_BYTES=$(stat -c %s engines/book.bin)
          if [ "$ACTUAL_BYTES" -gt "$MAX_BYTES" ]; then
            head -c $MAX_BYTES engines/book.bin > engines/book_trimmed.bin
            mv engines/book_trimmed.bin engines/book.bin
            echo "Trimmed book to 100MB"
          else
            echo "Book is under limit"
          fi

      - name: Commit downloaded book
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add engines/book.bin
          git commit -m "Add book.bin from PixelDrain"
          git push
