name: Download Ruy Lopez Book

on:
  workflow_dispatch:

jobs:
  download-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download from PixelDrain
        run: |
          mkdir -p engines
          curl -L "https://pixeldrain.com/api/file/gQziifHp" -o engines/ruylopez_book.bin

      - name: Show file size
        run: |
          ls -lh engines/ruylopez_book.bin

      - name: Trim to 100MB if too large (optional)
        run: |
          MAX_BYTES=$((100 * 1024 * 1024))
          ACTUAL_BYTES=$(stat -c %s engines/ruylopez_book.bin)
          if [ "$ACTUAL_BYTES" -gt "$MAX_BYTES" ]; then
            head -c $MAX_BYTES engines/ruylopez_book.bin > engines/book_trimmed.bin
            mv engines/book_trimmed.bin engines/ruylopez_book.bin
            echo "Trimmed book to 100MB"
          else
            echo "Book is under limit"
          fi

      - name: Commit and push downloaded book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add engines/ruylopez_book.bin
          git commit -m "Add Ruy Lopez opening book" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
