name: Read Polyglot Book

on:
  workflow_dispatch:

jobs:
  read-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install stockfish and Python tools
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish
          pip install chess polyglot

      - name: Generate FEN after e4 e5 Nf3 Nc6 Bb5
        run: |
          FEN=$(echo -e "position startpos moves e2e4 e7e5 g1f3 b8c6 f1b5\nd" | stockfish | grep "Fen:" | cut -d':' -f2 | xargs)
          echo "FEN=$FEN" >> $GITHUB_ENV
          echo "Using FEN: $FEN"

      - name: Read book.bin at given FEN
        run: |
          echo '
import chess
import polyglot.opening

fen = "'"$FEN"'"
board = chess.Board(fen)
print("Moves found in book at:", fen)

try:
    with polyglot.opening.Reader("engines/book.bin") as reader:
        found = False
        for entry in reader.find_all(board):
            print(f"Move: {entry.move()}, Weight: {entry.weight}, Learn: {entry.learn}")
            found = True
        if not found:
            print("No book moves found.")
except Exception as e:
    print("Error reading book:", e)
' > read_book.py

          python3 read_book.py
