name: Query Ruy Lopez Book Moves

on:
  workflow_dispatch:

jobs:
  query-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish
          pip install chess polyglot

      - name: Generate FEN for position
        id: generate_position
        run: |
          echo "position startpos moves e2e4 e7e5 g1f3 b8c6 f1b5" > position.txt
          FEN=$(stockfish < position.txt | grep "Fen:" | cut -d' ' -f2-)
          echo "FEN=$FEN" >> $GITHUB_ENV
          echo "Generated FEN: $FEN"

      - name: Query opening book
        run: |
          python3 <<EOF
import chess
import chess.polyglot
import os

fen = os.environ.get("FEN")
board = chess.Board(fen)
book_path = "engines/book.bin"

print(f"Querying book at: {board.fen()}")

try:
    with chess.polyglot.open_reader(book_path) as reader:
        entries = list(reader.find_all(board))
        if entries:
            for entry in entries:
                print(f"- {board.san(entry.move())} (weight: {entry.weight})")
        else:
            print("No book moves found")
except FileNotFoundError:
    print(f"Error: Book file not found at {book_path}")
EOF
